# Primeros pasos con Julia

## Temas a desarrollar
* Conseguir documentación
* Imprimir a pantalla
* Asignar variables
* Comentarios
* Matemática básica
* Casteo de tipos
* Strings
* Estructuras de datos
* Funciones
* Bucles

### Cómo conseguir documentación para funciones de Julia
Para conseguir documentación para funciones con las que uno no está familiarizado, hay que poner un signo de interrogación antes. (¡También funciona en la terminal!)

In [232]:
?isapprox

search: isapprox



```
isapprox(x, y; rtol::Real=atol>0 ? 0 : √eps, atol::Real=0, nans::Bool=false, norm::Function)
```

Inexact equality comparison: `true` if `norm(x-y) <= max(atol, rtol*max(norm(x), norm(y)))`. The default `atol` is zero and the default `rtol` depends on the types of `x` and `y`. The keyword argument `nans` determines whether or not NaN values are considered equal (defaults to false).

For real or complex floating-point values, if an `atol > 0` is not specified, `rtol` defaults to the square root of [`eps`](@ref) of the type of `x` or `y`, whichever is bigger (least precise). This corresponds to requiring equality of about half of the significand digits. Otherwise, e.g. for integer arguments or if an `atol > 0` is supplied, `rtol` defaults to zero.

`x` and `y` may also be arrays of numbers, in which case `norm` defaults to `vecnorm` but may be changed by passing a `norm::Function` keyword argument. (For numbers, `norm` is the same thing as `abs`.) When `x` and `y` are arrays, if `norm(x-y)` is not finite (i.e. `±Inf` or `NaN`), the comparison falls back to checking whether all elements of `x` and `y` are approximately equal component-wise.

The binary operator `≈` is equivalent to `isapprox` with the default arguments, and `x ≉ y` is equivalent to `!isapprox(x,y)`.

Note that `x ≈ 0` (i.e., comparing to zero with the default tolerances) is equivalent to `x == 0` since the default `atol` is `0`.  In such cases, you should either supply an appropriate `atol` (or use `norm(x) ≤ atol`) or rearrange your code (e.g. use `x ≈ y` rather than `x - y ≈ 0`).   It is not possible to pick a nonzero `atol` automatically because it depends on the overall scaling (the "units") of your problem: for example, in `x - y ≈ 0`, `atol=1e-9` is an absurdly small tolerance if `x` is the [radius of the Earth](https://en.wikipedia.org/wiki/Earth_radius) in meters, but an absurdly large tolerance if `x` is the [radius of a Hydrogen atom](https://en.wikipedia.org/wiki/Bohr_radius) in meters.

# Examples

```jldoctest
julia> 0.1 ≈ (0.1 - 1e-10)
true

julia> isapprox(10, 11; atol = 2)
true

julia> isapprox([10.0^9, 1.0], [10.0^9, 2.0])
true

julia> 1e-10 ≈ 0
false

julia> isapprox(1e-10, 0, atol=1e-8)
true
```


### Cómo imprimir
En Julia usamos println() para imprimir texto a la pantalla con un salto de línea, y print() para no agregar el salto de línea.

In [233]:
print("Hola ")
println("mundo!")

Hola mundo!


In [234]:
?printstyled

search: printstyled



```
printstyled([io], xs...; bold::Bool=false, color::Union{Symbol,Int}=:normal)
```

Print `xs` in a color specified as a symbol or integer, optionally in bold.

`color` may take any of the values `:normal`, `:default`, `:bold`, `:black`, `:blink`, `:blue`, `:cyan`, `:green`, `:hidden`, `:light_black`, `:light_blue`, `:light_cyan`, `:light_green`, `:light_magenta`, `:light_red`, `:light_yellow`, `:magenta`, `:nothing`, `:red`, `:reverse`, `:underline`, `:white`, or  `:yellow` or an integer between 0 and 255 inclusive. Note that not all terminals support 256 colors. If the keyword `bold` is given as `true`, the result will be printed in bold.


In [237]:
printstyled("👋🌎"; bold = true, color=:magenta)

👋🌎

In [238]:
🐍 = "Python"
print(🐍)

Python

### Cómo asignar variables
Al igual que en Python, el tipado es dinámico y no necesitas aclarar qué tipo de dato guarda una variable, Julia lo infiere automáticamente.

In [239]:
variable1 = 42
typeof(variable1)

Int64

In [240]:
variable2 = 3.14159
typeof(variable2)

Float64

In [241]:
variable3 = "Rosita"
typeof(variable3)

String

Podemos volver a asignar un valor de tipo diferente a una variable sin problemas.

In [242]:
variable1 = "Wachenchauzer"
typeof(variable1)

String

### Cómo comentar
Los comentarios de una linea se dejan con #, mientras que los multilinea se escriben como #= ... =#

In [243]:
# Una linea

In [244]:
#= 
Multi
Linea
=#

### Sintáxis para matemática básica

In [245]:
suma = 10 + 4

14

In [246]:
resta = 5 - 2

3

In [247]:
multiplicacion = 3 * 5

15

In [248]:
division = 6 / 3

2.0

In [249]:
cuadrado = 5 ^ 3

125

In [250]:
modulo = 101 % 2

1

### Casteo de tipos

In [251]:
resultado = 100 / 4

25.0

In [252]:
Int(resultado)

25

In [253]:
string(resultado)

"25.0"

In [261]:
cadena = "30"

"30"

In [262]:
parse(Int64, cadena)

30

### Manejo de strings
* Como definir una cadena
* Interpolación
* Concatenación

#### Definición

In [263]:
cadena_simple = "Hola mundo"

"Hola mundo"

In [264]:
cadena_ambigua = "El ejemplo clasico es imprimir "Hola Mundo", re aburrido"

LoadError: syntax: cannot juxtapose string literal

In [265]:
cadena_no_ambigua = """El ejemplo clasico es imprimir "Hola Mundo", re aburrido"""

"El ejemplo clasico es imprimir \"Hola Mundo\", re aburrido"

In [266]:
cadena_simple = 'Hola mundo'

LoadError: syntax: invalid character literal

In [267]:
caracter = 'A'
typeof(caracter)

Char

#### Interpolación

In [268]:
valorA = 10
valorB = 20

cadena = "Si el valorA es $valorA, y el valorB es $valorB, entonces dos veces valorA es $(valorA * 2)." 

"Si el valorA es 10, y el valorB es 20, entonces dos veces valorA es 20."

In [269]:
"2 * valorA es valorB? $(2*valorA === valorB)"

"2 * valorA es valorB? true"

In [272]:
?===

search: === == !==



```
===(x,y) -> Bool
≡(x,y) -> Bool
```

Determine whether `x` and `y` are identical, in the sense that no program could distinguish them. First the types of `x` and `y` are compared. If those are identical, mutable objects are compared by address in memory and immutable objects (such as numbers) are compared by contents at the bit level. This function is sometimes called "egal". It always returns a `Bool` value.

# Examples

```jldoctest
julia> a = [1, 2]; b = [1, 2];

julia> a == b
true

julia> a === b
false

julia> a === a
true
```


#### Concatenación

In [273]:
string("Hola", " ", "mundo", "!")

"Hola mundo!"

In [274]:
"Hola" * " " * "mundo" * "!"

"Hola mundo!"

In [275]:
"Hola " + "mundo!"

MethodError: MethodError: no method matching +(::String, ::String)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:502

### Estructuras de datos
* Tuplas
* Diccionario
* Arreglos

#### Tuplas

In [288]:
mis_materias_aprobadas = ("Algoritmos 1", "Algoritmos 2", "TDL")

("Algoritmos 1", "Algoritmos 2", "TDL")

In [289]:
typeof(mis_materias_aprobadas)

Tuple{String,String,String}

In [290]:
# 1-indexed!
mis_materias_aprobadas[1]

"Algoritmos 1"

In [291]:
# Inmutables
mis_materias_aprobadas[3] = "Teoría del Lenguaje"

MethodError: MethodError: no method matching setindex!(::Tuple{String,String,String}, ::String, ::Int64)

#### Diccionarios

In [310]:
miagenda = Dict("Ricky" => "12345678", "Fort" => "445334122", "Ffff" => 3)
miagenda2 = Dict(5 => 2)

Dict{Int64,Int64} with 1 entry:
  5 => 2

In [307]:
miagenda["Fort"]

"445334122"

In [308]:
miagenda["Julito"] = 1553350102
miagenda

Dict{String,Any} with 4 entries:
  "Ricky"  => "12345678"
  "Fort"   => "445334122"
  "Ffff"   => 3
  "Julito" => 1553350102

In [296]:
# Borra y devuelve el valor
pop!(miagenda, "Ricky")

"12345678"

In [297]:
miagenda

Dict{String,String} with 2 entries:
  "Fort"   => "445334122"
  "Julito" => "1553350102"

A diferencia de las tuplas y los arreglos, los diccionarios no están ordenados y no podemos accederlos con un índice

In [298]:
miagenda[1]

KeyError: KeyError: key 1 not found

#### Arreglos

In [299]:
mis_amigos = ["mi mamá", "mi tía"]

2-element Array{String,1}:
 "mi mamá"
 "mi tía" 

In [304]:
fibonacci = [1, 1, 2, 3, 5, 8, 13]

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [301]:
mezcla = [1, 1, 2, 3, "Ted", "Robyn"]

6-element Array{Any,1}:
 1       
 1       
 2       
 3       
  "Ted"  
  "Robyn"

Una vez que tenenmos un arreglo, podemos tomar los datos individualmente dentro del arreglo accediendolo por su índice. Por ejemplo, si queremos al segundo amigo en mis_amigos:

In [ ]:
mis_amigos[2]

Si queremos acceder al tercero, vamos a tener un BoundsError (IndexError en otros lenguajes, ConseguiteAmigosError en criollo).

In [ ]:
mis_amigos[3]

In [ ]:
push!(mis_amigos, "Otro amigo!")

In [ ]:
mis_amigos[3] = "mi tío"

In [ ]:
mis_amigos

In [ ]:
pop!(mis_amigos)

#### Arreglos multidimensionales

In [ ]:
A = rand(3,4)

In [ ]:
B = rand(3,4,2)

#### Referencia vs copia

In [ ]:
C = A
C[1] = 10
C === A

In [ ]:
C = copy(A)
C[3] = -1
C === A

### Funciones
* Cómo declarar una función
* Duck-typing en Julia
* Funciones mutables vs. no-mutables
* Broadcasting

#### Declaración
Clásica, single line y lambda.

In [226]:
function saludar(nombre)
    if (nombre === "Rosita")
        println("Hola $nombre Wachenchauzer!")
    elseif (nombre === "Leandro")
        println("Hola $nombre Ferrigno!")
    else
        println("Hola $nombre, gracias por venir")
    end
end

saludar (generic function with 1 method)

In [227]:
saludar("Tomi")

Hola Tomi, gracias por venir


In [228]:
saludar("Rosita")

Hola Rosita Wachenchauzer!


In [229]:
saludar("Leandro")

Hola Leandro Ferrigno!


In [163]:
elevar_al_cuadrado(x) = x ^ 2

elevar_al_cuadrado (generic function with 1 method)

In [164]:
elevar_al_cuadrado(10)

100

In [165]:
multiplicar_por_dos = y -> y * 2

#3 (generic function with 1 method)

In [166]:
multiplicar_por_dos(40)

80

#### Duck typing

In [230]:
saludar(20)

Hola 20, gracias por venir


In [168]:
elevar_al_cuadrado("Julia")

"JuliaJulia"

In [169]:
multiplicar_por_dos("Julia")

MethodError: MethodError: no method matching *(::String, ::Int64)
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:502
  *(!Matched::Complex{Bool}, ::Real) at complex.jl:300
  *(!Matched::Missing, ::Number) at missing.jl:93
  ...

Podemos definir qué tipo de dato esperamos recibir!

In [197]:
function saludar2(nombre :: String)
    println("Hola $nombre, gracias por venir")
end

saludar2 (generic function with 1 method)

In [198]:
saludar2("Tomi")

Hola Tomi, gracias por venir


In [199]:
saludar2(20)

MethodError: MethodError: no method matching saludar2(::Int64)
Closest candidates are:
  saludar2(!Matched::String) at In[197]:2

#### Funciones mutables vs no-mutables

In [176]:
lista_desordenada = [4,1,3,2]

4-element Array{Int64,1}:
 4
 1
 3
 2

In [177]:
sort(lista_desordenada)

4-element Array{Int64,1}:
 1
 2
 3
 4

In [178]:
lista_desordenada

4-element Array{Int64,1}:
 4
 1
 3
 2

In [179]:
sort!(lista_desordenada)

4-element Array{Int64,1}:
 1
 2
 3
 4

In [180]:
lista_desordenada

4-element Array{Int64,1}:
 1
 2
 3
 4

#### Broadcasting

In [184]:
elevar_al_cuadrado(lista_desordenada)

MethodError: MethodError: no method matching ^(::Array{Int64,1}, ::Int64)
Closest candidates are:
  ^(!Matched::Float16, ::Integer) at math.jl:795
  ^(!Matched::Missing, ::Integer) at missing.jl:120
  ^(!Matched::Missing, ::Number) at missing.jl:93
  ...

In [185]:
elevar_al_cuadrado.(lista_desordenada)

4-element Array{Int64,1}:
  1
  4
  9
 16

In [186]:
saludar(lista_desordenada)

Hola [1, 2, 3, 4], gracias por venir


In [191]:
saludar.(lista_desordenada);

Hola 1, gracias por venir
Hola 2, gracias por venir
Hola 3, gracias por venir
Hola 4, gracias por venir


### Bucles
* While
* For

#### While

In [204]:
i = 1
while i < 100
    print("$i ")
    i += 1
end

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

#### For

In [205]:
for i in 1:99
    print("$i ")
end

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

In [206]:
for v in [1,1,3,5,8,13]
    print("$v ")
end

1 1 3 5 8 13 

In [207]:
for c in "CADENA"
    print("$c")
end

CADENA

En vez de usar in podemos usar = o ∈

In [208]:
for c = "CADENA"
    print("$c")
end

CADENA

In [209]:
for c ∈ "CADENA"
    print("$c")
end

CADENA

Syntactic sugar para fors anidados

In [214]:
for i in 1:3, j in 7:9
    println("$i $j")
end

1 7
1 8
1 9
2 7
2 8
2 9
3 7
3 8
3 9


Crear arreglos mediante array comprehension

In [219]:
[i for i in 1:5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [221]:
L = ["$i$j" for i in 1:3, j in "ABC"]

3×3 Array{String,2}:
 "1A"  "1B"  "1C"
 "2A"  "2B"  "2C"
 "3A"  "3B"  "3C"